name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * SUN"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, ruby: head }
    name: test ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install musl
        run: |
          sudo apt install -qq build-essential musl-dev musl-tools
      - name: Fetch mruby source
        run: |
          git clone https://github.com/mruby/mruby.git mruby_source
      - name: Install build_config
        working-directory: ./mruby_source
        run: |
          rm -vf ./build_config/*.rb
          cp ../build_config/musl_linux_amd64.rb ./build_config/default.rb
      - name: Compile
        working-directory: ./mruby_source
        run: |
          rake
      - name: Test
        working-directory: ./mruby_source
        run: |
          rake test
